### ISSUE TITLE
Add code example to export NFA/DFA table as state diagram

### ISSUE THREAD

**Issue by SicroAtGit** [SicroAtGit/RegEx-Engine#20]
For this the tool [Graphviz](https://graphviz.org/) will be used.

For example, the following dot code for the regex `(a|b)` will be created:
```dot
digraph nfa_state_diagram {

	rankdir = LR;
	node [shape = circle];
	"" [shape = none, fixedsize = true, height = 0, width = 0];

	"" -> 1;

	1 -> 2 [label = "&epsilon;", style = dashed];

	2 -> 3 [label = "61"];

	3 -> 4 [label = "00"];

	4 -> 5 [label = "&epsilon;", style = dashed];

	5 [shape = doublecircle];

	1 -> 6 [label = "&epsilon;", style = dashed];

	6 -> 7 [label = "62"];

	7 -> 8 [label = "00"];
	
	8 -> 5 [label = "&epsilon;", style = dashed];
}
```
Graphviz then generates this NFA diagram visualization from the dot code:
![nfa](https://user-images.githubusercontent.com/18380976/177033969-bd074b92-aef5-4568-8e9d-a67369ba5fc1.png)

**Comment by tajmone** [comment]
This feature is really cool, but I suggest that you pack it into an extra optional module instead of the native library, because the native PB compiler doesn't optimize for dead code, which means that the code for the graphs would be included in the generated binary file even in applications that don't actually use it.

GCC does remove dead code from the final binary, but since we don't know the internals of the PB-GCC backend we can't be sure of this without experimenting whether this optimization is actually enforced.

**Comment by SicroAtGit** [comment]
I'll add it as code examples instead of a feature of the RegEx engine. With complex RegExes, the diagrams become very large and complex very quickly, and overload the "Graphviz" tool, so it's not really suitable as a serious feature.

**Comment by tajmone** [comment]
> With complex RegExes, the diagrams become very large and complex very quickly, and overload the "Graphviz" tool, so it's not really suitable as a serious feature.

Strange, in the past I used a tool for CYOA books which used Graphviz to draw the story paths and nodes, and it could handle pretty large graphs (these books could easily have 300 or more nodes).

**Comment by SicroAtGit** [comment]
The very complex RegEx character class `\w` results in an NFA with 10,442 states (nodes). If a DFA is created from it, it has 233 states (nodes) with a total of 46,241 connections (edges).

The dead state of the DFA is not counted in the numbers, otherwise there would be one more state and many more connections. But I don't show the dead state in the diagrams because it is not as interesting as the other states and because the diagrams would become too complex very quickly.

**Comment by SicroAtGit** [comment]
The very complex RegEx character class `\w` (ASCII or single-byte mode not activated) results in an NFA with 10,442 states (nodes). If a DFA is created from it, it has 233 states (nodes) with a total of 46,241 connections (edges).

The dead state of the DFA is not counted in the numbers, otherwise there would be one more state and many more connections. But I don't show the dead state in the diagrams because it is not as interesting as the other states and because the diagrams would become too complex very quickly.

It is probably the connections (edges) that take the longest time in Graphviz. I also use the dot layout engine in Graphviz, which is the slowest as far as I know. But the other layout engines don't produce good diagrams for NFA/DFA.

If an SVG file is created with Graphviz instead of a PNG file, the diagram is still readable (not reduced in size and pixelated). Firefox etc. can display such very large SVG files.

**Comment by SicroAtGit** [comment]
The very complex RegEx character class `\w` (ASCII or single-byte mode not activated) results in an NFA with 10,442 states (nodes). If a DFA is created from it, it has 233 states (nodes) with a total of 46,241 connections (edges).

The dead state of the DFA is not counted in the numbers, otherwise there would be one more state and many more connections. But I don't show the dead state in the diagrams because it is not as interesting as the other states and because the diagrams would become too complex very quickly.

It is probably the connections (edges) that take the longest time in Graphviz. I also use the dot layout engine in Graphviz, which is the slowest as far as I know. But the other layout engines don't produce good diagrams for NFA/DFA.

If an SVG file is created with Graphviz instead of a PNG file, the very complex diagrams are still readable (not reduced in size and pixelated). Firefox etc. can display such very large SVG files.

**Comment by SicroAtGit** [comment]
One possibility would be to simplify the state transitions of the DFA in the diagrams by using symbol ranges instead single symbols. Simplified example: Let's assume that state **A** moves to state **B** for the symbols `a`, `b`, `c`. In the diagram, the individual transitions for each symbol could be combined into one transition with the symbol range (`a` up to `c`). The simplified DFA representation in the diagram would then require far fewer connections between the nodes and Graphviz would have less work to do.
